


GET http://localhost:8080/posts/

###
POST http://localhost:8080/posts/
content-type: application/json

{
   "author":"wwsdgsdhsdhsdwwwt",
   "date": "2021-11-05T23:22:05.093Z",
  "title": "Hawefw",
  "description":"a",
  "content": "asdkgsdgkfjahsdg"
}

###
DELETE http://localhost:8080/posts/6185cee106b5aca886d24703
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjE4NzEzYjMwYWY1YWJiMmUzYjE4MDAzIiwibmFtZSI6IkpvaGFuIEpvaGFubnNvbiIsImlhdCI6MTYzNjI0NDM2MiwiZXhwIjoxNjM2MjUxNTYyfQ.9sknut_6WyOfHrt4AFqlSDU8oTIW0BZDWCIy2JNnOes


###
GET http://localhost:8080/posts/618718062e46c761371dd9c6

 
 
###
POST http://localhost:8080/login/
content-type: application/json

{
    "username":"Johan",
    "password":"123456"
  
}

###
GET http://localhost:8080/featured/
